# Generated by Django 5.0.6 on 2024-05-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='processing_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='excel_files/'),
        ),
    ]
